import { FD_CONSULT_URL, FD_NAME, FD_PRICE, FD_URL } from "./brand.ts";

export type SiteHost = "netlify" | "custom" | "github" | "vercel";
export type SiteStatusHint = "live" | "lab";
export type SiteCategory =
  | "flagship"
  | "ops"
  | "saas"
  | "field"
  | "infra"
  | "studio"
  | "lab";

export type HiveSite = {
  slug: string;
  name: string;
  url: string;
  github?: string;
  description: string;
  price?: string;
  category: SiteCategory;
  host: SiteHost;
  statusHint: SiteStatusHint;
  featured?: boolean;
};

export const HIVE_SITES: HiveSite[] = [
  {
    slug: "agenthive",
    name: "AgentHive Inc",
    url: "https://agenthiveinc.com/",
    description: `Palm Coast AI consultant shop. ${FD_NAME} and the live portfolio.`,
    category: "flagship",
    host: "custom",
    statusHint: "live",
    featured: true,
  },
  {
    slug: "first-deploy",
    name: FD_NAME,
    url: FD_URL,
    github: "https://github.com/PalmCoast/FirstDeploy",
    description: "After-hours desk and live apps for field operators. Live this week or you do not pay.",
    price: FD_PRICE,
    category: "ops",
    host: "custom",
    statusHint: "live",
    featured: true,
  },
  {
    slug: "consult",
    name: "Consult",
    url: FD_CONSULT_URL,
    description: "Free 30-minute qualifier, then paid time in the room.",
    price: "$75 / 30 min · $150 / hour · 10-hour pack $1,250",
    category: "ops",
    host: "custom",
    statusHint: "live",
    featured: true,
  },
  {
    slug: "claudefarm",
    name: "ClaudeFarm",
    url: "https://claudefarm.com/",
    description: `Public storefront for ${FD_NAME}, consult time, and live AgentHive Inc apps.`,
    category: "studio",
    host: "custom",
    statusHint: "live",
  },
  {
    slug: "ai-pricing",
    name: "AI Pricing Calculators",
    url: "https://aipricingcalculators.com/",
    description: "Free LLM API cost calculator, then the live AgentHive offers.",
    category: "saas",
    host: "custom",
    statusHint: "live",
  },
  {
    slug: "flick",
    name: "Flick",
    url: "https://flick.firstdeploy.ai/",
    description: "Browser screen recorder. Send a link. No login wall.",
    category: "saas",
    host: "custom",
    statusHint: "live",
    featured: true,
  },
  {
    slug: "jobproof",
    name: "JobProof",
    url: "https://jobproof.firstdeploy.ai/",
    description: "Proof the job happened — photos and timestamps, not another status meeting.",
    price: "Solo $49/mo · Crew $99/mo",
    category: "field",
    host: "custom",
    statusHint: "live",
    featured: true,
  },
  {
    slug: "indexme",
    name: "IndexMe.lol",
    url: "https://indexme.lol/",
    description: "Pay-to-stand index. Get the page found before you spend more on ads.",
    price: "Pro $19.99 · Studio $29.99 one-time",
    category: "saas",
    host: "custom",
    statusHint: "live",
    featured: true,
  },
  {
    slug: "tonight",
    name: "TONIGHT",
    url: "https://send-tonight.netlify.app/",
    description: "Paste the rate. Send tonight.",
    price: "$19.99 one-time",
    category: "field",
    host: "netlify",
    statusHint: "live",
  },
  {
    slug: "ratetrap",
    name: "RateTrap",
    url: "https://ratetrap.netlify.app/",
    description: "Catch the rate trap before you sign.",
    price: "$29.99 one-time",
    category: "field",
    host: "netlify",
    statusHint: "live",
  },
  {
    slug: "claimcash",
    name: "ClaimCash",
    url: "https://getclaimcash.netlify.app/",
    description: "Find unclaimed money.",
    price: "$5 finder",
    category: "saas",
    host: "netlify",
    statusHint: "live",
  },
  {
    slug: "stateside",
    name: "Stateside Jobs",
    url: "https://stateside-jobs.netlify.app/",
    github: "https://github.com/PalmCoast/no-ai-slop/tree/main/stateside",
    description: "US-authorized IT jobs board. Veterans get first look. $10 per posting.",
    price: "Free for seekers · $10/posting",
    category: "saas",
    host: "netlify",
    statusHint: "live",
  },
  {
    slug: "bot-lock",
    name: "Bot Lock",
    url: "https://bot-lock.netlify.app/",
    github: "https://github.com/PalmCoast/bot-lock",
    description: "Lock down agent and tool access. Policy, audit, least privilege.",
    category: "infra",
    host: "netlify",
    statusHint: "live",
    featured: true,
  },
  {
    slug: "hire-daniel",
    name: "Hire Daniel Graham",
    url: "https://hire-daniel-graham.netlify.app/",
    description: "Forward-deployed engineer who still sits with the work.",
    category: "ops",
    host: "netlify",
    statusHint: "live",
  },
  {
    slug: "writehive",
    name: "WriteHive",
    url: "https://writehive.netlify.app/",
    description: "AI word processor with RAID-0 document pooling across laptops on your Wi-Fi.",
    price: "$44.99 one-time",
    category: "saas",
    host: "netlify",
    statusHint: "live",
    featured: true,
  },
  {
    slug: "deskaudit",
    name: "DeskAudit",
    url: "https://deskaudit.netlify.app/",
    description: "Scan a site. Get a branded PDF covering SEO, security, performance, accessibility.",
    price: "$29 one-time",
    category: "saas",
    host: "netlify",
    statusHint: "live",
  },
  {
    slug: "hivebriefcase",
    name: "HiveBriefcase",
    url: "https://hivebriefcase.netlify.app/",
    github: "https://github.com/PalmCoast/agenthiveinc-hivebriefcase",
    description: "Portable identity and micropayments for AI agents. W3C DIDs, verifiable credentials, Base L2.",
    category: "infra",
    host: "netlify",
    statusHint: "live",
    featured: true,
  },
  {
    slug: "reviewhive",
    name: "ReviewHive",
    url: "https://reviewhive.netlify.app/",
    description: "One inbox for Google, Facebook, Play, App Store, and Tripadvisor reviews. Scores and drafts replies.",
    category: "saas",
    host: "netlify",
    statusHint: "live",
  },
  {
    slug: "nfc-review",
    name: "ReviewHive NFC",
    url: "https://nfc-review.netlify.app/",
    description: "NFC tap-to-review experience for crews that live on the truck, not in a dashboard.",
    category: "field",
    host: "netlify",
    statusHint: "live",
  },
  {
    slug: "socketsnap",
    name: "SocketSnap",
    url: "https://socketsnap.netlify.app/",
    github: "https://github.com/PalmCoast/vibemotion",
    description: "Camera-based bolt and nut measurement. Point, snap, size.",
    category: "field",
    host: "netlify",
    statusHint: "live",
  },
  {
    slug: "sonaris",
    name: "Sonaris",
    url: "https://sonaris-voice.netlify.app/",
    github: "https://github.com/PalmCoast/no-ai-slop/tree/main/sonaris",
    description: "Real-time voice layer for an AI assistant. Captions, turn-taking, persona voices, memory file.",
    category: "studio",
    host: "netlify",
    statusHint: "live",
  },
  {
    slug: "catcher",
    name: "CATCHER",
    url: "https://github.com/PalmCoast/catcher",
    github: "https://github.com/PalmCoast/catcher",
    description: "Paste a missed call, get the text to send back. No account. Hackyard Yard #1.",
    category: "lab",
    host: "github",
    statusHint: "lab",
  },
  {
    slug: "sidequest",
    name: "SideQuest",
    url: "https://github.com/PalmCoast/SideQuest",
    github: "https://github.com/PalmCoast/SideQuest",
    description: "Dating for busy engineers who might be shy.",
    category: "lab",
    host: "github",
    statusHint: "lab",
  },
  {
    slug: "fold-companion",
    name: "Fold Companion",
    url: "https://github.com/PalmCoast/no-ai-slop/tree/main/FoldCompanion",
    github: "https://github.com/PalmCoast/no-ai-slop/tree/main/FoldCompanion",
    description: "Android companion for the Galaxy Z Fold. Queues work off the phone. Never records calls.",
    category: "lab",
    host: "github",
    statusHint: "lab",
  },
  {
    slug: "pilemeter",
    name: "Tideview Pilemeter",
    url: "https://github.com/PalmCoast/tideview-pilemeter",
    github: "https://github.com/PalmCoast/tideview-pilemeter",
    description: "Point it at a pile of dirt. Get a volume.",
    category: "lab",
    host: "github",
    statusHint: "lab",
  },
  {
    slug: "clawlock-mcp",
    name: "Bot Lock MCP",
    url: "https://github.com/PalmCoast/clawlock-mcp-server",
    github: "https://github.com/PalmCoast/clawlock-mcp-server",
    description: "MCP-native identity, credential vault, and audit layer for AI agents. Pair with live Bot Lock.",
    category: "infra",
    host: "github",
    statusHint: "lab",
  },
];

export const NETLIFY_SITES = HIVE_SITES.filter((s) => s.host === "netlify");
