import type { GeneratedFile, NetworkPlan } from "./types.ts";

export function buildFiles(plan: NetworkPlan): GeneratedFile[] {
  const files: GeneratedFile[] = [
    { filename: "NETYARD-PLAN.md", mime: "text/markdown", contents: planMarkdown(plan) },
    { filename: "networks.csv", mime: "text/csv", contents: networksCsv(plan) },
    { filename: "hosts.csv", mime: "text/csv", contents: hostsCsv(plan) },
    { filename: "users.csv", mime: "text/csv", contents: usersCsv(plan) },
  ];
  if (plan.directory.mode !== "none") {
    files.push({
      filename: "install-office-server.sh",
      mime: "text/x-shellscript",
      contents: installScript(plan),
    });
  }
  if (plan.directory.mode === "samba-ad") {
    files.push({
      filename: "create-users.sh",
      mime: "text/x-shellscript",
      contents: createUsersScript(plan),
    });
  }
  if (plan.vpn) {
    files.push({
      filename: "wg0.conf",
      mime: "text/plain",
      contents: wireguardServer(plan),
    });
  }
  files.push({
    filename: "firewall.md",
    mime: "text/markdown",
    contents: firewallMarkdown(plan),
  });
  return files;
}

export function planMarkdown(plan: NetworkPlan): string {
  const { naming, answers, microsoft } = plan;
  const needs = answers.needs.join(", ");
  const nets = plan.networks
    .map(
      (n) =>
        `- ${n.name}${n.vlan ? ` (VLAN ${n.vlan})` : ""}: ${n.cidr} gateway ${n.gateway}` +
        (n.dhcpStart ? ` DHCP ${n.dhcpStart}–${n.dhcpEnd}` : " static only"),
    )
    .join("\n");
  const hosts = plan.hosts.map((h) => `- ${h.address}  ${h.name}  ${h.role}`).join("\n");
  const bom = plan.bom.map((b) => `- ${b.qty} × ${b.item} (~$${b.unitUsd} each) — ${b.notes}`).join("\n");
  const steps = plan.runbook.map((s, i) => `${i + 1}. **${s.title}** — ${s.detail}`).join("\n");
  const shares = plan.shares.map((s) => `- \`${s.name}\` ${s.path} — ${s.purpose}`).join("\n") || "- (no file shares)";
  return `# ${naming.businessName} network plan
Generated by NetYard (First Deploy AI). Street prices, not a quote.

${plan.summary}

## Answers
- People: ${answers.peopleCount} (${answers.headcount})
- Desktops: ${answers.desktops}
- Sites: ${answers.sites}
- Gear: ${answers.gear}
- Needs: ${needs}

## Directory
- Mode: ${plan.directory.mode}
- ${plan.directory.why}
${plan.directory.realm ? `- Realm: ${plan.directory.realm}  NetBIOS: ${naming.netbios}  DC: ${naming.dcFqdn}` : ""}
- Admin: ${plan.directory.adminUser}
- Password policy: ${plan.directory.passwordPolicy}

## Addressing
${nets}

## Reservations
${hosts}

## Shares
${shares}

## Wi-Fi
${plan.wifi.ssids.map((s) => `- ${s.name} on ${s.vlan} (${s.security})`).join("\n")}
- Access points: ${plan.wifi.apCount}

${plan.vpn ? `## VPN\n- WireGuard listen ${plan.vpn.listenPort}, server ${plan.vpn.serverAddress}, ${plan.vpn.peerCount} peers.\n- ${plan.vpn.notes}\n` : ""}
## Cost vs Microsoft Server
- Windows Server Standard + ${answers.peopleCount} User CALs ≈ $${microsoft.windowsTotalUsd}
- Samba licenses: $0
- Hardware in this plan ≈ $${microsoft.hardwareUsd}
- License money you keep: ≈ $${microsoft.savingsUsd}

${microsoft.notes.map((n) => `- ${n}`).join("\n")}

## Shopping list
${bom}

## Runbook
${steps}

## Warnings
${plan.warnings.map((w) => `- ${w}`).join("\n")}
`;
}

function networksCsv(plan: NetworkPlan): string {
  const header = "name,vlan,cidr,gateway,dhcp_start,dhcp_end,purpose";
  const rows = plan.networks.map((n) =>
    [n.name, n.vlan ?? "", n.cidr, n.gateway, n.dhcpStart ?? "", n.dhcpEnd ?? "", csv(n.purpose)].join(","),
  );
  return [header, ...rows].join("\n") + "\n";
}

function hostsCsv(plan: NetworkPlan): string {
  const header = "name,address,vlan,role,notes";
  const rows = plan.hosts.map((h) => [h.name, h.address, csv(h.vlan), csv(h.role), csv(h.notes)].join(","));
  return [header, ...rows].join("\n") + "\n";
}

function usersCsv(plan: NetworkPlan): string {
  const header = "username,first,last,group,ou";
  const rows = [
    "jdoe,Jane,Doe,Office,OU=Office",
    "mfield,Marco,Field,Field,OU=Field",
    "admin.shop,Shop,Admin,Shop Admins,OU=Admins",
  ];
  const extra = Math.min(plan.answers.peopleCount, 8);
  for (let i = 1; i <= extra; i += 1) {
    const n = String(i).padStart(2, "0");
    rows.push(`staff${n},Staff,${n},Office,OU=Office`);
  }
  return [header, ...rows].join("\n") + "\n";
}

function csv(value: string): string {
  if (/[",\n]/.test(value)) return `"${value.replace(/"/g, '""')}"`;
  return value;
}

function installScript(plan: NetworkPlan): string {
  const { naming, directory } = plan;
  const shares = plan.shares
    .filter((s) => s.path.startsWith("/"))
    .map((s) => `install -d -m 0770 -o root -g "Shop Admins" ${sh(s.path)}`)
    .join("\n");
  const provision =
    directory.mode === "samba-ad"
      ? `samba-tool domain provision \\
  --use-rfc2307 \\
  --realm=${sh(naming.realm)} \\
  --domain=${sh(naming.netbios)} \\
  --server-role=dc \\
  --dns-backend=SAMBA_INTERNAL \\
  --adminpass="$ADMIN_PASS"`
      : `cat >/etc/samba/smb.conf <<'EOF'
[global]
  workgroup = ${naming.netbios}
  server string = ${naming.businessName} files
  map to guest = never
  smb encrypt = desired
EOF`;

  return `#!/bin/bash
# NetYard office server bootstrap for ${naming.businessName}
# Target: Debian 12. Run as root on the box that will be ${naming.dcFqdn}.
set -euo pipefail

if [[ $(id -u) -ne 0 ]]; then
  echo "Run as root." >&2
  exit 1
fi
if [[ ! -f /etc/os-release ]] || ! grep -q 'ID=debian' /etc/os-release; then
  echo "This script expects Debian." >&2
  exit 1
fi
if [[ -z "\${ADMIN_PASS:-}" ]]; then
  echo "Set ADMIN_PASS to a 12+ character password before running." >&2
  exit 1
fi

HOSTNAME=${sh(naming.dcHostname)}
DOMAIN=${sh(naming.dnsDomain)}
FQDN=${sh(naming.dcFqdn)}
DC_IP=${sh(plan.hosts.find((h) => h.name === "dc01")?.address ?? "10.10.20.10")}

hostnamectl set-hostname "$HOSTNAME"
sed -i '/$FQDN/d' /etc/hosts
printf '%s\\t%s %s\\n' "$DC_IP" "$FQDN" "$HOSTNAME" >> /etc/hosts

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y samba samba-dsdb-modules samba-vfs-modules winbind libpam-winbind \\
  libnss-winbind krb5-user ntp smbclient dnsutils cups cups-client restic

systemctl disable --now systemd-resolved 2>/dev/null || true
rm -f /etc/resolv.conf
printf 'nameserver 127.0.0.1\\nnameserver 1.1.1.1\\nsearch %s\\n' "$DOMAIN" > /etc/resolv.conf

systemctl stop smbd nmbd winbind samba 2>/dev/null || true
mv /etc/samba/smb.conf /etc/samba/smb.conf.bak.$(date +%s) 2>/dev/null || true

${provision}

${directory.mode === "samba-ad" ? sambaAdFinish(plan, shares) : workgroupFinish(plan, shares)}
`;
}

function sambaAdFinish(plan: NetworkPlan, shares: string): string {
  const { naming } = plan;
  return `ln -sf /var/lib/samba/private/krb5.conf /etc/krb5.conf
systemctl unmask samba-ad-dc 2>/dev/null || true
systemctl enable --now samba-ad-dc ntp cups

samba-tool domain passwordsettings set --complexity=on --min-pwd-length=12 --max-pwd-age=180 || true
samba-tool ou create "OU=Shop,${ldap(naming.dnsDomain)}" || true
samba-tool ou create "OU=Office,OU=Shop,${ldap(naming.dnsDomain)}" || true
samba-tool ou create "OU=Field,OU=Shop,${ldap(naming.dnsDomain)}" || true
samba-tool ou create "OU=Admins,OU=Shop,${ldap(naming.dnsDomain)}" || true
${plan.directory.groups.map((g) => `samba-tool group add ${sh(g)} || true`).join("\n")}

${shares || "true"}

echo "Join Windows PCs to ${naming.realm}. DNS for those PCs must be $DC_IP."
echo "Create people with: ADMIN_PASS=… ./create-users.sh users.csv"`;
}

function workgroupFinish(plan: NetworkPlan, shares: string): string {
  const shareStanzas = plan.shares
    .filter((s) => s.path.startsWith("/"))
    .map(
      (s) => `
[${s.name}]
  path = ${s.path}
  read only = no
  valid users = @office @field shopadmin
  create mask = 0660
  directory mask = 0770`,
    )
    .join("\n");
  return `printf 'nameserver %s\\nnameserver 1.1.1.1\\n' ${sh(plan.networks[0]?.gateway ?? "1.1.1.1")} > /etc/resolv.conf
cat >>/etc/samba/smb.conf <<'EOF'
${shareStanzas}
EOF
useradd -m shopadmin 2>/dev/null || true
echo "shopadmin:$ADMIN_PASS" | chpasswd
(echo "$ADMIN_PASS"; echo "$ADMIN_PASS") | smbpasswd -a shopadmin
${shares || "true"}
systemctl enable --now smbd nmbd ntp cups
echo "Map shares as shopadmin on ${plan.naming.dcFqdn}."`;
}

function createUsersScript(plan: NetworkPlan): string {
  return `#!/bin/bash
# Create Samba users from users.csv (username,first,last,group,ou)
set -euo pipefail
FILE=\${1:-users.csv}
if [[ -z "\${ADMIN_PASS:-}" ]]; then
  echo "Set ADMIN_PASS." >&2
  exit 1
fi
if [[ ! -f "$FILE" ]]; then
  echo "Missing $FILE" >&2
  exit 1
fi
tail -n +2 "$FILE" | while IFS=, read -r username first last group ou; do
  [[ -z "$username" || "$username" == username ]] && continue
  samba-tool user create "$username" --random-password --given-name="$first" --surname="$last" --userou="$ou,OU=Shop,${ldap(plan.naming.dnsDomain)}" || true
  samba-tool user setexpiry "$username" --noexpiry || true
  samba-tool group addmembers "$group" "$username" || true
  echo "created $username in $group"
done
`;
}

function wireguardServer(plan: NetworkPlan): string {
  const vpn = plan.vpn!;
  return `# WireGuard on the firewall, not on the DC.
# Generate keys on the firewall: wg genkey | tee server.key | wg pubkey > server.pub
[Interface]
Address = ${vpn.serverAddress}
ListenPort = ${vpn.listenPort}
PrivateKey = REPLACE_WITH_SERVER_PRIVATE_KEY
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o WAN_IF -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o WAN_IF -j MASQUERADE

# Repeat a [Peer] block per laptop. AllowedIPs on the client: 10.10.80.0/24, Staff, Servers.
# Do not route Guest, IoT, or POS to VPN users unless you have a reason.
[Peer]
PublicKey = REPLACE_WITH_PEER_PUBLIC_KEY
AllowedIPs = 10.10.80.2/32
`;
}

function firewallMarkdown(plan: NetworkPlan): string {
  const rows = plan.firewall.map((r) => `| ${r.from} | ${r.to} | ${r.action} | ${r.ports} | ${r.reason} |`).join("\n");
  return `# Firewall matrix for ${plan.naming.businessName}

| From | To | Action | Ports | Why |
| --- | --- | --- | --- | --- |
${rows}

WAN inbound stays closed. If you publish WireGuard, allow UDP ${plan.vpn?.listenPort ?? 51820} to the firewall only.
`;
}

function sh(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function ldap(domain: string): string {
  return domain
    .split(".")
    .map((label) => `DC=${label}`)
    .join(",");
}
