export type AppCategory = "ops" | "field" | "saas" | "infra" | "studio";

export type SaleApp = {
  slug: string;
  name: string;
  url: string;
  price: string;
  blurb: string;
  who: string;
  category: AppCategory;
  featured?: boolean;
};

export const SALE_APPS: SaleApp[] = [
  {
    slug: "first-deploy",
    name: "First Deploy AI",
    url: "https://firstdeploy.ai/",
    price: "$1,500 setup, then $250/mo",
    blurb: "After-hours desk plus live apps for dirt, plants, and shops. Live this week or you do not pay the setup.",
    who: "Owners who miss night calls",
    category: "ops",
    featured: true,
  },
  {
    slug: "consult",
    name: "Consult",
    url: "https://firstdeploy.ai/consult",
    price: "$75 / 30 min · $150 / hour · 10-hour pack $1,250",
    blurb: "Free 30-minute qualifier, then paid time in the room.",
    who: "Anyone who wants a human on the job",
    category: "ops",
    featured: true,
  },
  {
    slug: "jobproof",
    name: "JobProof",
    url: "https://jobproof.firstdeploy.ai/",
    price: "Solo $49/mo · Crew $99/mo",
    blurb: "Proof the job happened — photos and timestamps, not another status meeting.",
    who: "Crews that get argued with about whether they showed up",
    category: "field",
    featured: true,
  },
  {
    slug: "flick",
    name: "Flick",
    url: "https://flick.firstdeploy.ai/",
    price: "Free to send a link",
    blurb: "Browser screen recorder. Send a link. No login wall.",
    who: "Anyone explaining a job over the phone",
    category: "saas",
    featured: true,
  },
  {
    slug: "indexme",
    name: "IndexMe.lol",
    url: "https://indexme.lol/",
    price: "Pro $19.99 · Studio $29.99 one-time",
    blurb: "Honest IndexNow indexing desk. Get the page found before you spend more on ads.",
    who: "Shops that rebuilt a site and still do not show up",
    category: "saas",
    featured: true,
  },
  {
    slug: "tonight",
    name: "TONIGHT",
    url: "https://send-tonight.netlify.app/",
    price: "$19.99 one-time",
    blurb: "Paste the rate. Send tonight.",
    who: "Dispatchers who still text rates by hand",
    category: "field",
  },
  {
    slug: "ratetrap",
    name: "RateTrap",
    url: "https://ratetrap.netlify.app/",
    price: "$29.99 one-time",
    blurb: "Catch the rate trap before you sign.",
    who: "Owner-ops reading a contract at 9 p.m.",
    category: "field",
  },
  {
    slug: "claimcash",
    name: "ClaimCash",
    url: "https://getclaimcash.netlify.app/",
    price: "$5 finder",
    blurb: "Find unclaimed money.",
    who: "Anyone who moved and left a deposit behind",
    category: "saas",
  },
  {
    slug: "stateside",
    name: "Stateside Jobs",
    url: "https://stateside-jobs.netlify.app/",
    price: "Free for seekers · $10/posting",
    blurb: "US-authorized IT jobs board. Veterans get first look.",
    who: "US IT people who are done with recruiter spam",
    category: "saas",
  },
  {
    slug: "writehive",
    name: "WriteHive",
    url: "https://writehive.netlify.app/",
    price: "$44.99 one-time",
    blurb: "AI word processor with RAID-0 document pooling across laptops on your Wi-Fi.",
    who: "Offices that still pass Word files around",
    category: "saas",
  },
  {
    slug: "deskaudit",
    name: "DeskAudit",
    url: "https://deskaudit.netlify.app/",
    price: "$29 one-time",
    blurb: "Scan a site. Get a branded PDF covering SEO, security, performance, accessibility.",
    who: "Owners who got a scary SEO pitch",
    category: "saas",
  },
  {
    slug: "bot-lock",
    name: "Bot Lock",
    url: "https://bot-lock.netlify.app/",
    price: "Talk to us",
    blurb: "Lock down agent and tool access. Policy, audit, least privilege.",
    who: "Shops that already let an agent touch live tools",
    category: "infra",
  },
  {
    slug: "reviewhive",
    name: "ReviewHive",
    url: "https://reviewhive.netlify.app/",
    price: "Talk to us",
    blurb: "One inbox for Google, Facebook, Play, App Store, and Tripadvisor reviews. Scores and drafts replies.",
    who: "Front desks drowning in one-star nights",
    category: "saas",
  },
  {
    slug: "nfc-review",
    name: "ReviewHive NFC",
    url: "https://nfc-review.netlify.app/",
    price: "Talk to us",
    blurb: "NFC tap-to-review for crews that live on the truck, not in a dashboard.",
    who: "Trucks that want a five-star tap on the way out",
    category: "field",
  },
  {
    slug: "socketsnap",
    name: "SocketSnap",
    url: "https://socketsnap.netlify.app/",
    price: "Talk to us",
    blurb: "Camera-based bolt and nut measurement. Point, snap, size.",
    who: "Mechanics tired of guessing socket size",
    category: "field",
  },
  {
    slug: "sonaris",
    name: "Sonaris",
    url: "https://sonaris-voice.netlify.app/",
    price: "$29 one-time license",
    blurb: "Talk to an AI out loud. It captions, waits, and answers in a voice you pick.",
    who: "People who hate typing on a job site",
    category: "studio",
  },
  {
    slug: "claudefarm",
    name: "ClaudeFarm",
    url: "https://claudefarm.com/",
    price: "Storefront",
    blurb: "Public storefront for First Deploy AI, consult time, and live AgentHive Inc apps.",
    who: "Buyers who want the whole shelf in one place",
    category: "studio",
  },
  {
    slug: "aipricing",
    name: "AI Pricing Calculators",
    url: "https://aipricingcalculators.com/",
    price: "Free calculator",
    blurb: "Free LLM API cost calculator, then the live AgentHive offers.",
    who: "Anyone about to buy tokens blind",
    category: "saas",
  },
];

export const FEATURED_APPS = SALE_APPS.filter((app) => app.featured);
